name: Clang Format On Push

on: push

jobs:
  Block-If-Not-Formatted:
    runs-on: ubuntu-latest
    steps:
      - name: Update apt repos
        run: sudo apt update
      - name: Install clang format
        run: sudo apt install clang-format
      - name: Get current git repo
        uses: actions/checkout@v3
      - name: Check clang format
        run: |
          if $(find . -type f -iname "*.cpp" -o -iname "*.hpp" | xargs clang-format  --dry-run --Werror -style=WebKit) ; then exit 0; else exit 1; fi
